### ISSUE TITLE
Plugin migration takes away default group if player is in any child group of it

### ISSUE THREAD

**Issue by aviadmini** [ChubbyQuokka/Loone-Permissions#4]

**Comment by ChubbyQuokka** [comment]
I believe I had implemented it this way on purpose, as the player already inherits the permissions and it just produces more SQL calls.

**Comment by aviadmini** [comment]
The problem is that I don't get the default groups migrated and thus don't get the permissions from it

**Comment by ChubbyQuokka** [comment]
So the default group just isn't getting migrated at all?

**Comment by aviadmini** [comment]
Yes, players don't get the default groups because other groups inherit from it. And they don't get permissions too

**Comment by ChubbyQuokka** [comment]
Alright, I'll take a look at it. Thanks for notifying me about this.

**Comment by ChubbyQuokka** [comment]
I believe it is fixed, you may need to do some testing tho.

**Comment by aviadmini** [comment]
Thanks.

Does it migrate every group that player has now? Because that's what it is supposed to do

**Comment by ChubbyQuokka** [comment]
Yes, I believe that it should now.
